version: 2.1
jobs:
  linux-build:
    working_directory: ~/github.com/confluentinc/confluent-kafka-go
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.16
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    environment:
      # - GOBIN="$GOPATH/bin"
      - EXPECT_LINK_INFO="dynamic"
      - BUILD_TYPE='-tags dynamic'
      # Figure out how to set paths
      # - PKG_CONFIG_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib/pkgconfig"
      # - LD_LIBRARY_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib"
      # - DYLD_LIBRARY_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib"
      - LIBRDKAFKA_VERSION=master

    steps:
      - checkout
      # - run: wget -qO - https://packages.confluent.io/deb/5.4/archive.key | sudo apt-key add -
      - run: go version
      - run: sudo apt-get update -q
      - run: sudo apt-get install confluent-librdkafka-plugins -y
      - run: echo which go
      - run: go get -u golang.org/x/lint/golint && touch .do_lint

  macos-build:
    macos:
      xcode: "9.2"
    steps:
      - run: echo "hello world macos"

workflows:
  doit:
    jobs:
      - linux-build
      - macos-build
