version: 2.1
jobs:
  linux-build:
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.16
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - run:
          name: Linux step
          command: |
            echo 'Hello World Linux!'
  macos-build:
    macos:
      xcode: "9.2"
    steps:
      - run: echo "hello world macos"

workflows:
  doit:
    jobs:
      - linux-build
      - macos-build
