version: 2.1
jobs:
  linux-build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Linux step
          command: |
            echo 'Hello World Linux!'
  macos-build:
    macos:
      xcode: "9.2"
    steps:
      - run: echo "hello world macos"

workflows:
  doit:
    jobs:
      - linux-build
      - macos-build

